print( )  #[Tela]
type('') #[Mostra os tipos]
input( ) #[Digitar]
abs( ) #[mostra o valor absoluto]
pow( ) #[Radiação]
dir( ) #[mosrta oq tá incorporado]
sorted( ) #[Ordem crescente]
max( ) #[Mostra o maximo de tupla/lista sendo número ou nome]
round( ) #[Arrendonda pro número mais perto]
divmod( ) #[Mostra a Divisão ex: x = divmod(72, 6) (12, 0)]
id( ) #[Mostra um ID único pra cada objeto, muda toda vez q é iniciado o programa]
ord( ) #[Mostra o ID único padrão de palavras ou letras]
len( ) #[Mostra o quantas palavras tem na lista/tupla ou quantas letras tem na palavra ]
sum( ) #[Soma todos os números de uma lista/tupla]
help( ) #[Ajuda a saber a função
dict().copy()#[Ajuda a copiar em dict
list().append()#[Adiciona no final da lista]
